
-----------------------------
SELECT COUNT(*) from TUKYONLINE 

SELECT * from TUKYONLINE 


--1
DELETE FROM TUKYONLINE_TEMP
--2
INSERT INTO TUKYONLINE_TEMP
SELECT DISTINCT URL FROM TUKYONLINE
--3
DELETE FROM TUKYONLINE 
--4
INSERT INTO TUKYONLINE
SELECT URL,NOW() FROM TUKYONLINE_TEMP

